# A short, descriptive name of this building block collection
name: Sensor Things API Building Blocks

# Short abstract for this collection (optional)
abstract: |
  This is set of data building blocks describing reusable components of the Sensor Things API 1.1.  Building blocks provide elements that may be reused, and mappings to the underlying OMS model via the SOSA ontology. 

# Description for this collection (optional)
description: |
  Initial work on the bblocks extraction was done for the particular cases of the Iliad project.
  This initial draft can be missing some elements of the STA and relax on some formal constraints for the better support of the JSON Schema, OpenAPI 3.0.1 and JSON-LD specifications.
  The mapping of schema elements to formal definitions (JSON-LD context files) shall be treated as draft proposition.

identifier-prefix: ogc.api.sta.

imports:
  - default
