# A short, descriptive name of this building block collection
name: Sensor Things API building blocks

# Short abstract for this collection (optional)
abstract: |
  This is set of data building blocks used by the Sensor Things API 1.1.

# Description for this collection (optional)
description: |
  Initial work on the bblocks extration was done for the particular cases of the Iliad project.
  It can be missing some elements of the STA and relax on some formal contraints for the better support of the JSON Schema, OpenAPI 3.0.1 and JSON-LD speifications.
  The mapping to the context files is the proposed one and shall be treated as draft proposition.

identifier-prefix: ogc.bbr.sta.

imports:
  - default
