"$schema": http://json-schema.org/draft-04/schema#
title: Coverage object
description: 'Schema for Sensor things API 1.3 Observation'
type: object
properties:
  "@iot.id":
      type: integer
      description: The Id of the observation
  "@iot.selfLink":
      type: string
      description: The direct link to the entity
  parameters:
    type: object
  phenomenonTime:
    type: string
    description: The time when the observation happened. or Time Interval string (e.g., 2010-12-23T10:20:00.00-07:00 or 2010-12-23T10:20:00.00-07:00/2010-12-23T12:20:00.00-07:00)
  result:
    type: string
    description: The estimated value of the observed property. Type depends on the observationType defined in the associated Datastream
  resultQuality:
    type: string
    description: A description of the quality of the result. Type DQ_Element.
  resultTime:
    type: string
    description: The time the result was generated. TM_Instant (ISO 8601 Time string)
  validTime:
    type: string
    description: The time period during which the result can be used. TM_Period (ISO 8601 Time Interval string)
  Datastream@iot.navigationLink:
    type: string
    description: Reference link to the DataStream Definition.
  FeatureOfInterest@iot.navigationLink:
    type: string
    description: Reference link to the FeatureOfInterest.
