"$schema": "http://json-schema.org/draft-04/schema#"
title: Datastream object
description: "Schema for Sensor things API 1.3 Datastream"
type: object
properties:
  "@iot.id":
      type:
        - string
        - number
      description: The Id of the observation
  "@iot.selfLink":
      type: string
      description: The direct link to the entity
  "Observations@iot.navigationLink":
    type: string
    description: Reference link to stream of Observations.

