"$schema": "http://json-schema.org/draft-04/schema#"
title: ObservedProperty object
description: "Schema for ObservedProperty entity in OGC SensorThings API 1.3"
type: object
properties:
  "@iot.id":
    description: The Id of the ObservedProperty
  "@iot.selfLink":
    type: string
    description: The direct link to the ObservedProperty entity
  name:
    type: string
    description: A label for the ObservedProperty, commonly a short descriptive name.
  definition:
    type: string
    format: uri
    description: A URI that defines the observed phenomenon (e.g., from a controlled vocabulary or ontology).
  description:
    type: string
    description: Detailed description of the ObservedProperty.
  Datastreams@iot.navigationLink:
    type: string
    description: Reference link to related Datastream entities.

required:
  - "@iot.id"
  - "@iot.selfLink"
  - name
  - definition
  - description
