"$schema": "http://json-schema.org/draft-04/schema#"
title: Sensor object
description: "Schema for Sensor things API 1.3 Observation"
type: object
properties:
  "@iot.id":
      description: The Id of the sensor
  "@iot.selfLink":
      type: string
      description: The direct link to the entity
  properties:
    type: object
    description: A JSON Object containing user-annotated properties as key-value pairs.
  name:
    type: string
    description: A property provides a label for Sensor entity, commonly a descriptive name.
  description:
    type: string
    description: The description of the Sensor entity.
  encodingType:
    type: string
    description: The encoding type of the metadata property. Its value is one of the ValueCode enumeration (see Table 15 for the available ValueCode).
  metadata:
    description: The detailed description of the Sensor or system. The metadata type is defined by encodingType.
  Datastream@iot.navigationLink:
    type: string
    description: Reference link to the DataStream Definition.
